using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class scriptLaser : MonoBehaviour
{
    LineRenderer line;

    // Start is called before the first frame update
    void Start()
    {

        line = gameObject.GetComponent<LineRenderer>();
        line.enabled = false;

    }

    // Update is called once per frame
    void Update()
    {

        if (Input.GetButtonDown("Fire1"))
        {
            StopCoroutine("FireLaser");
            StartCoroutine("FireLaser");
        }

    }

    IEnumerator FireLaser()
    {
        line.enabled = true;

        while (Input.GetButton("Fire1")) { 
            Ray ray = new Ray(transform.position, transform.forward);

            RaycastHit hit;

            line.SetPosition(0, ray.origin);

            if (Physics.Raycast(ray, out hit, 100))
            {
                line.SetPosition(1, hit.point);

                if (hit.rigidbody)
                {
                    hit.rigidbody.AddForceAtPosition(transform.forward * 100, hit.point);
                }
            }
            else
            {
                line.SetPosition(1, ray.GetPoint(100));
            }

            
            yield return null;
        }
        line.enabled = false;
    }
}
